export const fonts = {
	"PlusJakartaSans-Light": require("../assets/fonts/PlusJakartaSans-Light.ttf"),
	"PlusJakartaSans-LightItalic": require("../assets/fonts/PlusJakartaSans-LightItalic.ttf"),
	"PlusJakartaSans-ExtraLight": require("../assets/fonts/PlusJakartaSans-ExtraLight.ttf"),
	"PlusJakartaSans-ExtraLightItalic": require("../assets/fonts/PlusJakartaSans-ExtraLightItalic.ttf"),
	"PlusJakartaSans-Regular": require("../assets/fonts/PlusJakartaSans-Regular.ttf"),
	"PlusJakartaSans-Medium": require("../assets/fonts/PlusJakartaSans-Medium.ttf"),
	"PlusJakartaSans-MediumItalic": require("../assets/fonts/PlusJakartaSans-MediumItalic.ttf"),
	"PlusJakartaSans-SemiBold": require("../assets/fonts/PlusJakartaSans-SemiBold.ttf"),
	"PlusJakartaSans-SemiBoldItalic": require("../assets/fonts/PlusJakartaSans-SemiBoldItalic.ttf"),
	"PlusJakartaSans-Bold": require("../assets/fonts/PlusJakartaSans-Bold.ttf"),
	"PlusJakartaSans-BoldItalic": require("../assets/fonts/PlusJakartaSans-BoldItalic.ttf"),
	"PlusJakartaSans-ExtraBold": require("../assets/fonts/PlusJakartaSans-ExtraBold.ttf"),
	"PlusJakartaSans-ExtraBoldItalic": require("../assets/fonts/PlusJakartaSans-ExtraBoldItalic.ttf"),
}